version: "3.9"
services:
  raiko:
    build:
      context: ../
      dockerfile: ./Dockerfile
      args:
        BUILD_FLAGS: ""
    image: raiko:latest
    container_name: raiko
    command: --config-path=/etc/opt/raiko/config.toml
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"
    volumes:
      - /secrets:/opt/raiko/secrets
      - /tmp/sgx:/tmp/sgx
      - /var/log/raiko:/var/log/raiko
