version: "3.9"
services:
  raiko:
    build:
      context: ../
      dockerfile: ./Dockerfile
      args:
        BUILD_FLAGS: ""
    image: raiko:latest
    container_name: raiko
    ports:
      - "8085:8085"
    command: --config-path=/etc/opt/raiko/config.toml
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"
    volumes:
      - ${HOME}/.config/raiko/secrets:/opt/raiko/secrets
      - /tmp/sgx:/tmp/sgx
      - /var/log/raiko:/var/log/raiko
    ports:
      - "8080:8080"
